### ISSUE TITLE
termux-api on FDroid is not updated

### ISSUE THREAD

**Issue by ilyapashuk** [termux/termux-api#328]
FDroid version of termux-api app is much older then googleplay version, it is not updated together with googleplay version.

**Comment by xeffyr** [comment]
There is a tag & actual version mismatch and I guess that confused F-Droid build bot. From git history (https://github.com/termux/termux-api/commits/master/app/build.gradle) there is a direct upgrade from v0.38 to v0.41.

**Comment by xalexalex** [comment]
Yep, my fault. Luckily fornwall pointed it out to me a few days ago and it was fixed with v0.41, which is not out on f-droid yet. I'll close this issue as soon as it hits the f-droid repos.

**Comment by xeffyr** [comment]
F-Droid [updated](https://gitlab.com/fdroid/fdroiddata/-/commit/e70b83ef92332561e46ffdf08e4ca62628da890c) metadata, so v0.41 should be available soon:
```
  - versionName: '0.38'
    versionCode: 38
    commit: v0.38
    subdir: app
    gradle:
      - yes
    prebuild: sed -i -e '/signingConfig/d' build.gradle

  - versionName: '0.41'
    versionCode: 41
    commit: v0.41
    subdir: app
    gradle:
      - yes
    prebuild: sed -i -e '/signingConfig/d' build.gradle
```
